demistify ports: updated jtcore2

diff --git a/modules/jtframe/bin/jtcore2 b/modules/jtframe/bin/jtcore2
--- a/modules/jtframe/bin/jtcore2
+++ b/modules/jtframe/bin/jtcore2
@@ -20,7 +20,10 @@
 function show_usage() {
     cat << EOF
 JTCORE compilation tool. (c) Jose Tejada 2019-2023, @topapate
-    Argument without - is the core name, like gng, or 1943
+usage: jtcore <corename> [options]
+
+    jtcore compiles only one core at a time. To compile many cores at once
+    use jtupdate.
 
     Macro definition
     --def | -d   Defines a verilog macro. Macros are removed from qsf file after
@@ -327,17 +330,15 @@ fi
 
 OUTPUTDIR=output_files
 
-# Check Quartus path       #somhi# added neptuno & sidi to Quartus 17 path
+# Check Quartus path
 case $TARGET in
-    mister|sockit|de1soc|de10std|neptuno|sidi|demistify)
-        if ! (which quartus_sh|grep intelFPGA_lite -q); then
+    mist) # MiST can only be compiled on Quartus 13, which is slower on systems with many CPU cores
+        if ! (which quartus_sh|grep 13 -q); then
             PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:.
-            if [ -d /opt/intelFPGA_lite ]; then
-                cd /opt/intelFPGA_lite
-                cd $(ls | head -n 1)
-                PATH=$PATH:`pwd`/quartus/bin
+            if [ -d "/opt/altera/13.1" ]; then
+                PATH=$PATH:/opt/altera/13.1/quartus/bin
             else
-                echo "Cannot find Quartus in /opt/intelFPGA_lite (`hostname`)"
+                echo "Cannot find Quartus 13 in /opt/altera/13.1 (`hostname`)"
                 exit 1
             fi
         fi;;
@@ -346,12 +347,14 @@ case $TARGET in
             echo "" #No need for Quartus for this target"
         fi;;
     *)
-        if ! (which quartus_sh|grep 13 -q); then
+        if ! (which quartus_sh|grep intelFPGA_lite -q); then
             PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:.
-            if [ -d "/opt/altera/13.1" ]; then
-                PATH=$PATH:/opt/altera/13.1/quartus/bin
+            if [ -d /opt/intelFPGA_lite ]; then
+                cd /opt/intelFPGA_lite
+                cd $(ls | head -n 1)
+                PATH=$PATH:`pwd`/quartus/bin
             else
-                echo "Cannot find Quartus 13 in /opt/altera/13.1 (`hostname`)"
+                echo "Cannot find Quartus in /opt/intelFPGA_lite (`hostname`)"
                 exit 1
             fi
         fi;;
@@ -447,6 +450,7 @@ corename=${CORENAME,,}
 
 if (eval parse_macros bash | grep JTFRAME_SKIP > /dev/null); then
     echo "Compilation skipped for $TARGET because of JTFRAME_SKIP"
+    echo "Use -u JTFRAME_SKIP to override this."
     echo "PASS"
 #   exit 0				#somhi# comment out to avoid JTFRAME_SKIP
 fi
@@ -455,7 +459,15 @@ START_TIME=$(date +%s)
 echo =============== JTCORE =======================
 echo -e "${wBG}$CORENAME $TARGET compilation ${blue}starts${NC}${wBG} at ${red}$(date +%T)${NC}${wBG} with seed ${red}$SEED${NC}${wBG} on $(hostname)${NC}"
 if [ "$MACROS" != "" ]; then
-    echo Explicit macros: $MACROS
+    echo -e Explicit macros:
+    for i in $MACROS; do
+        if [ ${i:0:17} != JTFRAME_UNLOCKKEY ]; then
+            echo -n "$i "
+        else # Do not print the key value
+            echo -n "JTFRAME_UNLOCKKEY "
+        fi
+        echo
+    done
 fi
 
 ################ compilation
@@ -517,55 +529,65 @@ if [ $SKIP_COMPILE = FALSE ]; then
     if [ $SIM = FALSE ]; then
         # Create the QIP file
         jtframe mem $PRJ --target=$TARGET || exit $?
+        jtframe mmr $PRJ
         jtframe files syn $PRJ --target=$TARGET
         # Compilation
         if test $TARGET = zx3a200 || test $TARGET = zx3a100 || test $TARGET = zx3a35; then
             echo "" #No need for Quartus for this target"   #somhi# mod
         else
-            quartus_sh --flow compile $corename > "$LOG"
-            if ! grep "Full Compilation was successful" "$LOG"; then
-                grep -i error "$LOG" -A 2
-                echo -e "${rBG}ERROR:${NC}${wBG} while compiling the project. ${red}Aborting${NC}"
-                report FAIL
-                exit 1         
-            fi
-            if [ ! -e $corename.map.rpt ]; then
-                RPTPATH=$OUTPUTDIR
-            else
-                RPTPATH=.
-            fi
-            grep "SDRAM_.* is stuck" $RPTPATH/$corename.map.rpt | grep "SDRAM_[^\"]*" -o > $RPTPATH/sdram_stuck.rpt
-            gawk -f $JTFRAME/bin/jtioreg.awk $RPTPATH/$corename.fit.rpt > $RPTPATH/sdram_io.rpt
-            cat $RPTPATH/sdram_stuck.rpt $RPTPATH/sdram_io.rpt | sort | uniq --unique > sdram_badio.rpt
-            if [ -s sdram_badio.rpt ]; then
-                echo -e "${yBG}WARNING:${NC}${wBG} some SDRAM signals are not IO registers${NC}"
-                cat sdram_badio.rpt
-            fi
-            if grep "inferring latch" $RPTPATH/jt$PRJ.map.rpt; then
-                echo "Warning: latch inferred"
-            fi
-            # Report FPGA usage
-            if [ -e $RPTPATH/*.fit.summary ]; then
-                grep "Total logic" $RPTPATH/*.fit.summary
-                grep "Total memory" $RPTPATH/*.fit.summary
-            fi
-            # Report connectivity problems
-            grep \^Warning $LOG | grep \\.v | grep -v altera_pll\\.v \
-            | grep -v altera_cyclonev_pll\\.v \
-            | grep -v "\.data_a.*has no driver or initial value" \
-            | grep -v "\.waddr_a.*has no driver or initial value" \
-            | grep -v "\.we_a.*has no driver or initial value"
-            # Report timing
-            grep --color=auto "Worst-case.*-[0-9.]*" "$LOG"
-            if [[ $? = 0 && -z "$SKIPTIMING" ]]; then
-                FAIL=1
-                report FAIL
-                echo FAIL $PRJ
-            else
-                echo PASS
-                report PASS
-            fi
-        fi
+		    quartus_sh -v
+		    quartus_sh --flow compile $corename > "$LOG"
+		    if ! grep "Full Compilation was successful" "$LOG"; then
+		        grep -i error "$LOG" -A 2
+		        echo -e "${rBG}ERROR:${NC}${wBG} while compiling the project. ${red}Aborting${NC}"
+		        report FAIL
+		        exit 1
+		    fi
+		    if [ ! -e $corename.map.rpt ]; then
+		        RPTPATH=$OUTPUTDIR
+		    else
+		        RPTPATH=.
+		    fi
+		    grep "SDRAM_.* is stuck" $RPTPATH/$corename.map.rpt | grep "SDRAM_[^\"]*" -o > $RPTPATH/sdram_stuck.rpt
+		    gawk -f $JTFRAME/bin/jtioreg.awk $RPTPATH/$corename.fit.rpt > $RPTPATH/sdram_io.rpt
+		    cat $RPTPATH/sdram_stuck.rpt $RPTPATH/sdram_io.rpt | sort | uniq --unique > sdram_badio.rpt
+		    if [ -s sdram_badio.rpt ]; then
+		        echo -e "${yBG}WARNING:${NC}${wBG} some SDRAM signals are not IO registers${NC}"
+		        cat sdram_badio.rpt
+		    fi
+		    if grep "inferring latch" $RPTPATH/jt$PRJ.map.rpt; then
+		        echo "Warning: latch inferred"
+		    fi
+		    # Report FPGA usage
+		    if [ -e $RPTPATH/*.fit.summary ]; then
+		        grep "Total logic\|Logic utilization" $RPTPATH/*.fit.summary
+		        grep "Total memory\|Total RAM" $RPTPATH/*.fit.summary
+		    fi
+		    # Report connectivity problems
+		    AUX=`mktemp`
+		    grep \^Warning $LOG | grep \\.v | grep -v altera_pll\\.v \
+		    | grep -v altera_cyclonev_pll\\.v \
+		    | grep -v "\.data_a.*has no driver or initial value" \
+		    | grep -v "\.waddr_a.*has no driver or initial value" \
+		    | grep -v "\.we_a.*has no driver or initial value" > $AUX
+		    if [[ "$MACROS" == *MISTER_DEBUG_NOHDMI* ]]; then
+		        # There are many warnings coming from sys_top when HDMI is disabled, ignore them.
+		        grep -v sys_top.v $AUX
+		    else
+		        cat $AUX
+		    fi
+		    rm -f $AUX
+		    # Report timing
+		    grep --color=auto "Worst-case.*-[0-9.]*" "$LOG"
+		    if [[ $? = 0 && -z "$SKIPTIMING" ]]; then
+		        FAIL=1
+		        report FAIL
+		        echo FAIL $PRJ
+		    else
+		        echo PASS
+		        report PASS
+		    fi
+		fi
     else
         # Simulation
         echo Preparing simulation netlist. Logfile:
@@ -701,15 +723,6 @@ if [[ ( "$GIT" = FALSE || (( is_mister_family || $TARGET = pocket || "$BETA" != 
         sed -i /$RELEASE/d  $BINFOLDER/version.log
     fi
     printf "%-24s %s\n" ${RELEASE} $PRJCOMMIT >> $BINFOLDER/version.log
-
-    if is_mister_family; then
-        OTHER=$(append_if_exists $JTROOT/doc/$corename.md $JTROOT/cores/$PRJ/README.md $JTROOT/README.md $JTROOT/README.txt )
-        # remove blanks
-        OTHER=${OTHER## }
-        if [ ! -z "$OTHER" ]; then
-            cp $OTHER $BINFOLDER;
-        fi
-    fi
     cd - > /dev/null
 elif [ ! -z "$VERBOSE" ]; then
     echo "Skipping copy to JTBIN or release"
